### ISSUE TITLE
Add an option to output detected issues as JSON

### ISSUE THREAD

**Issue by kevinbarabash** [somewhatabstract/checksync#634]
**Is your feature request related to a problem? Please describe.**
I'd like to use checksync to build an eslint plugin for linting sync tags.

**Describe the solution you'd like**
A `--json` option that would output any issues detected in a file as a JSON blob.

**Describe alternatives you've considered**
I considered a direct API, but implementing a `--json` option should be easier since it shouldn't require any changes to how checksync is packaged.

**Comment by kevinbarabash** [comment]
I think the following structure for the JSON output could work:
```
[{
   type: "error",
   file: "services/static/javascript/app-shell-package/app-entry.js",
   line: 14,
   message: "Sync-start for 'app-shell-entry' points to 'services/static/webpack/plugins/make-i18n-html-pages.jsx', which does not exist or is a directory",
}, {
   type: "mismatch",
   file: "services/static/javascript/app-shell-package/app-entry.js",
   line 14,
   message: "Looks like you changed the target content for sync-tag 'app-shell-entry' in 'services/static/webpack/plugins/make-i18n-html-pages.js:80'. Make sure you've made the parallel changes in the source file, if necessary (0 != 2118575972)",
   fix: "// sync-start:app-shell-entry 2118575972 services/static/webpack/plugins/make-i18n-html-pages.js",
}]
```

**Comment by somewhatabstract** [comment]
I think the file should also include the arguments used to execute checksync so that it contains all the data needed to recreate the run. That way, if we so chose, we could update checksync to read this format too and know exactly how to interpret all the paths and such.

**Comment by somewhatabstract** [comment]
Also, including the version of checksync would be useful - just in case we decided to change the format.
